### ISSUE TITLE
Type 'typeof ResultAsync' is not a valid async function return type

### ISSUE THREAD

**Issue by bluenote10** [supermacro/neverthrow#179]
I'm having trouble with my very first steps with this library. I'm trying something very simple like:

```ts
async function foo(): Promise<number> {
  return 42;
}

async function test(): ResultAsync<string, Error> {
  let result = await ResultAsync.fromPromise(foo(), () => new Error("failed"))
  if (result.isOk()) {
    if (result.value > 0) {
      return okAsync("positive")
    } else {
      return okAsync("negative")
    }
  } else {
    return errAsync(new Error("failed"))
  }
}
```

However the compiler complains with:

```
Type 'typeof ResultAsync' is not a valid async function return type in ES5/ES3 because it does not refer to a Promise-compatible constructor value.
  Types of parameters 'res' and 'executor' are incompatible.
    Type '(resolve: (value?: T | PromiseLike<T> | undefined) => void, reject: (reason?: any) => void) => void' is missing the following properties from type 'Promise<Result<unknown, unknown>>': then, catch, [Symbol.toStringTag], finally  TS1055

    55 | }
    56 | 
  > 57 | async function test(): ResultAsync<string, Error> {
       |                        ^
    58 |   let result = await ResultAsync.fromPromise(foo(), () => new Error("failed"))
    59 |   if (result.isOk()) {
    60 |     if (result.value > 0) {
```

Somehow I can't combine the `async` with `ResultAsync`. But if I remove `async` Typescript obviously does not allow to use `await`, which means I cannot get access to the result value.

Am I missing something or is this a tsconfig thing? This is in a pretty plain create-react-app typescript template.

**Update**: Even if I set `"target": "es6"` in the compiler options I get:

```
The return type of an async function or method must be the global Promise<T> type. Did you mean to write 'Promise<Result<string, Error>>'?  TS1064

    55 | }
    56 | 
  > 57 | async function test(): ResultAsync<string, Error> {
       |                        ^
    58 |   let result = await ResultAsync.fromPromise(foo(), () => new Error("failed"))
    59 |   if (result.isOk()) {
    60 |     if (result.value > 0) {
```

**Comment by supermacro** [comment]
@bluenote10 this is something I admittedly have not a good job of documenting. I'll reference https://github.com/supermacro/neverthrow/issues/38 so that I don't forget to better document this "drawback" / "gotcha". 

Anyways, what's happening is the following:

When you mark a function as `async` you're implying that the function returns a `Promise<T>`. Hence, the type definition for `test` is invalid. 

What you must do this this:

```typescript
const test = (): ResultAsync<string, Error> =>
  ResultAsync.fromPromise(
    foo(),
    () => new Error("failed")
  )
  .map(result =>
    result.value > 0 
      ? "positive"
      :  "negative"
  )
```

I've also taken the liberty to implement the same function in what I would deem to be a more "idiomatic" way haha (the functionality remains the same).

**Comment by supermacro** [comment]
Hey @bluenote10,

I will be closing this issue in the coming days. Let me know if you have any further comments / concerns / criticisms / questions 🙂

**Comment by bluenote10** [comment]
I see, thanks! Indeed, in general simply chaining with `map` is the best solution.

I also noticed that I can use `async` if I annotate the return type as `Promise<Result<string, Error>>` instead. I assume the downside of doing this is that the function signature no longer expresses "I can never throw", because it becomes a regular promise again, and the user in theory has to deal with the possibility of failed state (which cannot really happen when returning `ResultAsync` internally I guess).

I simply had a few use cases where I needed `async` because I had to await multiple async results, or because the function should have some "awaited" side effects. Or how would you for instance solve the following?

```ts
async function foo(): Promise<number> {
  return 42;
}

async function combine(): Promise<Result<number, Error>> {
  let promiseA = foo();
  let promiseB = foo();
  let resultA = await ResultAsync.fromPromise(promiseA, () => new Error("failed"))
  let resultB = await ResultAsync.fromPromise(promiseB, () => new Error("failed"))
  return (
    resultA.isOk() && resultB.isOk() ?
    okAsync(resultA.value + resultB.value) :
    errAsync(new Error("failed"))
  )
}
```

If I would spawn the second promise within `map` or `andThen` I would lose some parallelism from not spawning them simultaneously, right?

**Comment by supermacro** [comment]
> I also noticed that I can use async if I annotate the return type as Promise<Result<string, Error>> instead... 

The downside isn't necessarily that the function doesn't express that it will never throw. In fact, the `ResultAsync` was a later addition to `neverthrow`, and prior to that I used `Promise<Result<T, E>>` amply. And in that case I used to assume that the `Promise` would never throw. It's a matter of conventions for each individual team / developer. 

The real downside is that you now have a plain old `Promise` instead of a `ResultAsync`, which means you cannot `map` the inner `Result` or call `andThen` or `unwrapOr`, etc. ... so you lose versatility and composition by returning `Promise`.

> how would you for instance solve the following?

My general convention (which you can see lots of examples for [in my side project](https://github.com/parlez-vous/server/blob/master/src/db/actions.ts#L54)) is to create functions that call `ResultAsync.fromPromise` in order to ensure all my async functions that may fail are returning a `ResultAsync`.

You can also define an anonymous async function inside of `fromPromise`:

```typescript
ResultAsync.fromPromise(
  async () => {..},
  catchPromise
)
```

Thus I would have the following:

```typescript
import { Result, ResultAsync, combine } from 'neverthrow'

async function foo(): Promise<number> {
  return Math.floor(Math.random() * 100)
}

const foo_ = (): ResultAsync<number, Error> =>
  ResultAsync.fromPromise(
    foo(),
    () => new Error('failed')
  )


const sumValus = (vals: number[]): number =>
  vals.reduce(
    (sum, num) => sum + num,
    0
  )

const bar = async (): Promise<Result<number, unknown>> => {
  const results = await Promise.all([
    foo_(),
    foo_(),
    foo_(),
  ])


  return combine(results).map(sumValus)
}


bar().then(result => console.log(result))
```

### You need to have the latest @beta version of `neverthrow` in order to use `ResultAsync` inside of `Promise.all` + have the `combine` function. 

```
npm install neverthrow@2.8.0-beta.1
```

Docs on `combine` can be found here:

https://github.com/supermacro/neverthrow/releases/tag/v2.8.0-beta.0
