### ISSUE TITLE
Add function docs to help users who are using intellisense or other language servers for inline documentation.

### ISSUE THREAD

**Issue by supermacro** [supermacro/neverthrow#187]
Context: https://github.com/supermacro/neverthrow/issues/38#issuecomment-658385438

**Comment by Liam-Tait** [comment]
I'm happy to do some work on this given a direction.

I suggest two parts are added to each inline comment

1. A short description of what the unit of code does
2. `@param` description for each parameter

I don't think this needs to be as detailed or exactly the same as the README. Especially since this would double documentation maintenance by having two sources of truth.  Clear and concise descriptions should do

Suggest this is split into a pr for each code unit and progressively add these docs

**Comment by supermacro** [comment]
Hey @Liam-Tait, yeah that works great. As long as [tsdoc](https://github.com/Microsoft/tsdoc) conventions are followed, I'm happy!

One thing I'm just realizing may be a challenge is the fact that methods are implemented twice for the `Result` type (once for `Ok` and again for `Err`), so just something to keep in mind and see how it works with intellisense features.

**Comment by Liam-Tait** [comment]
This took awhile for me to get back to. Happy to be assigned this task.

I have created a draft pr @supermacro

**Comment by supermacro** [comment]
Improvement is now live: https://github.com/supermacro/neverthrow/releases/tag/v4.2.1

Note that `ResultAsync` and the utils functions are not yet abiding by this format, but this is a great start. I'll eventually get around to update `ResultAsync` and `utils`.
