### ISSUE TITLE
The combine function creates warnings

### ISSUE THREAD

**Issue by bliksemman** [supermacro/neverthrow#191]
The `combine` function generates warnings because of it's usage of `ResultAsync.fromPromise`:

https://github.com/supermacro/neverthrow/blob/a0dc6dbe458f393d0dfb6eae6ac61f755c5e2950/src/utils.ts#L24

This results in a lot of log messages during development (which obfuscate actual problems in my code). What would be the best way to address this?

**Comment by supermacro** [comment]
It should be ok for `combineResultAsyncList` to be updated to pass in a `dummyErrorHandler` into the `fromPromise` function call to remove those logs. 

Alternatively, there could be an environment variable that `neverthrow` uses to silence these logs.

From: https://github.com/supermacro/neverthrow/blob/master/src/_internals/log.ts

```
if (process.env.NEVERTHROW_IGNORE_LOGS) {
  return
}
```

I don't know if I'll have time this week to work on patching this, but PRs are always welcome!

**Comment by paduc** [comment]
I'm sensing a bit of code smell with the code around this helper. In this context, the `Promise.all` promise cannot throw, because it is an array of `ResultAsync`. We should not have to provide a `dummyErrorHandler`.

The problem comes from the fact that the helper is called "from the outside" and does not have access to the inner promise of `ResultAsync`. 

Implementing `combine` as a method of `ResultAsync` would allow to create a new `ResultAsync` with the `Promise.all` as the inner promise.

**Comment by supermacro** [comment]
I'm beginning to think that the `fromPromise` function should **always** catch the containing promise regardless of whether a `errorFn` is passed in or not. 

If a `errorFn` is not passed in, then internally `fromPromise` would use a identity function and convert `E` to be `unknown`.

This would allow `fromPromise` to remove the need to log anything at all. 

However I wasn't able to implement a solution that would compile. But I thought I would share my idea here for feedback.

**Comment by supermacro** [comment]
Hey @paduc do you recall why the `errorFn` argument for `fromPromise` as made optional to begin with? Maybe there's something important that I'm forgetting.

**Comment by paduc** [comment]
Hi @supermacro, I sincerly don't remember. It seems to be optional since its introduction. 

I like your proposal to always catch and change the error type to `unknown` when `errorFn` is not provided.

I've been using it a lot and have always ended up providing an `errorFn` so I don't see why it couldn't become mandatory.

**Comment by supermacro** [comment]
Found some [context](https://github.com/supermacro/neverthrow/pull/34#discussion_r425793749)! 

It looks like we assumed that the caller of `fromPromise` might already do their own error handling, thus not requiring the user to pass in a `errorFn` argument. Although, in my opinion, this seems like a antipattern when using `neverthrow`.

**Comment by paduc** [comment]
> Found some [context](https://github.com/supermacro/neverthrow/pull/34#discussion_r425793749)!
> 
> It looks like we assumed that the caller of `fromPromise` might already do their own error handling, thus not requiring the user to pass in a `errorFn` argument. Although, in my opinion, this seems like a antipattern when using `neverthrow`.

I agree. I believe it's safest to catch the error while transforming the throwable method into a result. I don't see the point of having both a `try/catch` and a call to `fromPromise` with an `errorFn`.

**Comment by supermacro** [comment]
Solved in this latest release:

https://github.com/supermacro/neverthrow/releases/tag/v4.0.0
