### ISSUE TITLE
Convert Array of Result<T,E> to Result<T,E[]>

### ISSUE THREAD

**Issue by afontcu** [supermacro/neverthrow#197]
Hi! First of all, thanks for this library. I'm starting to learn how to deal with it, and found a situation I'm not sure how to handle. 

Use case: I want to validate a UI field, and print **all** failed validations. So, I think I need to convert an array of Results to a result with an array of errors.

```ts
const validateMinLength = (s: string) =>
  s.length > 8 ? ok(s) : err('too short')

const validateStrength = (s: string, getStrength: (s: string) => number) =>
  getStrength(s) > 25 ? ok(s) : err('too weak')
```

What's the best way to combine those results, and either return `s` if everything is fine or `['too short', 'too weak']` if both validations failed (so, without short-circuiting)?

Thanks! 🙌

**Comment by supermacro** [comment]
Hey @afontcu, 

If I understand correctly, you have a UI field that contains some data represented by a type `T` and that field contains one or more validation rules, which I'll represent by a type `E[]`.

Having an initial `Array<Result<T, E>>` doesn't make sense to me because you're saying, "I may have one or more `T` values for my single UI field".

So what I would think you need is something like this:

```typescript
type ErrorMessage = string

type Validator<T> = (val: T) => ErrorMessage | null

const validateMinLength = (s: string):  =>
  s.length <= 8 ? 'too short' : null

const validateStrength = (getStrength: (s: string) => number) => (s: string): ErrorMessage | null =>
  getStrength(s) <= 25 ? 'too weak' : null

const validateMyField = <T>(validators: Validator<T>, val: T): ErrorMessage[] =>
  validators.reduce(
    (errors, validator) =>
      const maybeError = validator(val)
      
     if (maybeError) {
        return [...errors, maybeError]
     }
    
     return errors
  , [])
```

With this you can then have logic that takes a UI field value of type `T` and returns a `Result<T, E[]>`

**Comment by afontcu** [comment]
Sounds good :) I guess I was trying to "fit" my idea into Result, but it wasn't meant for that.

Thank you for your time! Appreciated.
