### ISSUE TITLE
Any best practices for testing with Jest?

### ISSUE THREAD

**Issue by bluenote10** [supermacro/neverthrow#211]
I'm using Jest as a test framework. My naive attempts at writing tests for functions that return a `Result` typically look like:

```ts
expect(callSomeFunction("with", "some", "args")).isOk()).toEqual(true);
expect(callSomeFunction("with", "some", "args"))._unsafeUnwrap()).toEqual(someExpectation);
```

This is a bit clumsy because:
- I need to double all test calls just for the `isOk()` and `_unsafeUnwrap()` parts. Especially if the `callSomeFunction("with", "some", "args")` expression is long, this causes quite some overhead.
- When the function fails, the runner only outputs that `isOk()` wasn't `true`. Any helpful information in the error object remains hidden. I frequently copy paste the expression into a third line for an ad-hoc `console.log` just to get some information, which of course feels wrong ;).
- Using `_unsafeUnwrap` and `_unsafeUnwrapErr` basically everywhere looks a bit ugly and feels like an anti-pattern.

I'm be no means a Jest expert and still have to check if it offers something that could help here.

I just wanted to bring up the topic, perhaps there are already some better approaches?

**Comment by supermacro** [comment]
> Using _unsafeUnwrap and _unsafeUnwrapErr basically everywhere looks a bit ugly and feels like an anti-pattern.

I have been considering removing these methods for a while. But now I'm realizing that they make great testing utilities. 

I think that usage of `_unsafeUnwrap` and `_unsafeUnwrapErr` in "real code" (outside of tests) is definitely an antipattern, however they make for great testing utilities. 

Here's why I think this:

- Both `_unsafeUnwrap` and `_unsafeUnwrapErr` **imply** that a value is either a `Ok` or an `Err` ... otherwise they throw
  - Right now, when these methods throw, [they don't provide info on what value they actually contain](https://github.com/supermacro/neverthrow/blob/master/src/result.ts#L83) .. they just say "woops something went wrong" - so this could be improved for sure.
  - There could also be a new method called `toJson` or something along those lines which might be useful for testing / debugging, along with serialization or other use cases. 

- By using `_unsafeUnwrap` or `_unsafeUnwrapErr` you don't need to duplicate code.

```typescript
expect(callSomeFunction("with", "some", "args"))._unsafeUnwrap()).toEqual(someExpectation);

// the above also implies that you expect callSomeFunction to return a Ok value
//
// so you don't need `expect(callSomeFunction("with", "some", "args")).isOk()).toEqual(true);`
```

I recall having a similar discussion with a colleague earlier this year and he had some reservations about only depending on `_unsafeUnwrap` and `_unsafeUnwrapErr`, but I don't recall his exact reasoning. I do recall that I didn't agree though 😇

What do you think?

**Comment by supermacro** [comment]
Come to think of it. I'm pretty sure that it's convention in Rust to `.unwrap()` (or `.unwrap_err()`) the result in tests.

**Comment by bluenote10** [comment]
> Right now, when these methods throw, they don't provide info on what value they actually contain .. they just say "woops something went wrong" - so this could be improved for sure.

Yes, I think this is the biggest problem currently, and the main reason why I actually have to duplicate all the test statements. I think it is crucial for TDD to have a clear error even in the case where the actual test failure is because of an `Ok` vs `Error` mismatch.

> Come to think of it. I'm pretty sure that it's convention in Rust to .unwrap() (or .unwrap_err()) the result in tests.

Yes that isn't uncommon. I just checked: Rust does show the underlying value in both cases of `Ok` vs `Error` mismatchs, so there is never a need to duplicate the test just to get that information as well:

![image](https://user-images.githubusercontent.com/3620703/102807118-63ac1000-43be-11eb-8258-8e480ccaf770.png)

![image](https://user-images.githubusercontent.com/3620703/102807228-8dfdcd80-43be-11eb-8e96-da90ba179027.png)

This leaves the syntactical overhead: `._unsafeUnwrap()` and `._unsafeUnwrapErr()` have 16 / 19 characters overhead compared to a non-result based test case (i.e. exception relying API), which is a bit much. The main optical issue is probably the combination of the underscore plus the `unsafe`. If these function would become official and follow the Rust convention of "an unwrap is always unsafe", they could probably be simplified to `.unwrap()` and `.unwrapErr()`, which would bring the testability of `Result` based APIs much closer to exception APIs.

Another thought: Would it actually be possible to make this work?
```ts
expect(callSomeFunction("with", "some", "args"))).toEqual(ok(someExpectation));
```
This would have the least overhead syntactically. Currently it doesn't work because of the identity of the `match` function though. And I'm not sure about the readability in the `ok` vs `err` mixup case.

**Comment by supermacro** [comment]
Seems like there are some action items here:

- [ ] Log more useful information when throwing exceptions within `_unsafeUnwrap` and `_unsafeUnwrapErr`
- [ ] Consider renaming `_unsafeUnwrap` to `unwrap` and `_unsafeUnwrapErr` to `unwrapErr`
  - Not yet sure how I feel about this. I really like the explicit naming. In addition, the fact that they are cumbersome to write should detract from their usage in non-test environments. Unlike in Rust, `Result`s are not very well known in the JS / TypeScript community. Hence, shortening their name to `unwrap` and `unwrapErr` may lead to frustration for users who are not that familiar with the conventions established in Rust and other languages. 

I played around with Jest and neverthrow and couldn't find a way to do a "deep" comparisson that would work with the `Ok` and `Err` class instances. 

Hence I think a final action item would be:

- [ ] Implement a `equals` method on `Result` (and potentially on `ResultAsync`) with the following type signature:

```typescript
   Ok<T, E>.equals<U, F>(other: Result<U, F>): other is Ok<T, F> { ... }
   
  Err<T, E>.equals<U, F>(other: Result<U, F>): other is Err<U, E> { ... }
```

**Comment by supermacro** [comment]
I intentionally left the error value as `F` and the success value as `U` for `Ok.equals` and `Err.equals`, respectively, because different type arguments do not necessarily  imply different types. i.e. `T` and `U` *could* be the same, but not necessarily. Same with `E` and `F`. 

This might lead to confusing compilation errors if the caller of `.equals` is not aware of this fact. And I think it might lead to annoying boilerplate such as having to call `.mapErr` if `T` and `U` are in fact not the same. Or having to call `.map` if `E` and `F` are not the same.

So, my gut tells me it would be more sensical to change the types to:

```typescript
  Ok<T, E>.equals<U, F>(other: Result<U, F>): other is Ok<T, E> { ... }
   
  Err<T, E>.equals<U, F>(other: Result<U, F>): other is Err<T, E> { ... }
```

**Comment by paduc** [comment]
I also use `unsafeUnwrap` for testing, but only for `Result`s that are not part of the area being tested, ie only for results that I have built for the test case but that I know should always be `Ok`.

For the `Result` that I am testing, I check `.isOk()` directly.

example:
```typescript
const myFakeUser = User.create(fakeUserData)._unsafeUnwrap() // This always passes

const result = await myTestedMethod(myFakeUser); // This is what I am testing
expect(result.isOk()).toBe(true);
if(result.isErr()) return; // I have to add this for the next lines to pass the compiler
expect(result.value).toHaveProperty("foo");
// ...
```

For me, the most painful part is the fact that the compiler doesn't infer that my result is `Ok` from `expect(result.isOk()).toBe(true)` so I have to add a superfluous line to tell the compiler that it is. I've seen discussion about this in jest and the conclusion seemed to be that couldn't be addressed for now.

I'm personally wary of removing the `unsafe` mentions in the method names because it would be harder to spot the abuse of unsafe unwraps outside of tests.

**Comment by supermacro** [comment]
Continuing the conversation from https://github.com/supermacro/neverthrow/pull/215 

I just pushed an update: https://github.com/supermacro/neverthrow/commit/c230296035226630fbe2591939af84e7c9bb0bc3

Unfortunately, generating a stack trace via `(new Error()).trace` was causing confusing output in Jest error messages. So I omitted the addition of stack traces.

**Comment by supermacro** [comment]
Here's a proposed non-breaking change that would allow for generating stack traces in the event that these methods are being used outside of tests and a caller wants stack traces:

https://github.com/supermacro/neverthrow/pull/217/files

**Comment by bluenote10** [comment]
Cool, thanks for all the fixes.

To summarize the best practices for future readers here: After the changes it is now possible to simply "bring the `ok` / `err` to the other side", i.e.:

```ts
expect(callSomeFunction("with", "some", "args"))).toEqual(ok(someExpectation));
```

Alternatively this can be used:

```ts
expect(callSomeFunction("with", "some", "args"))._unsafeUnwrap()).toEqual(someExpectation);
```

Both approaches should now print very good error messages if a test case returns an `ok` where an `err` is expected or vice versa.

Now that this works, I would advice against using a combination of
```ts
expect(result.isOk()).toBe(true);
expect(result.value).toHaveProperty("foo");
```
Not only does it bloat the test code unnecessarily, but it also hides the crucial failure information behind an uninformative `false was not true` failure stemming from the `isOk()` check.

**Comment by supermacro** [comment]
Thanks @bluenote10, I'll add this info to the readme when I get a chance.

And happy holidays! 🎄

**Comment by paduc** [comment]
> Now that this works, I would advice against using a combination of
> 
> ```ts
> expect(result.isOk()).toBe(true);
> expect(result.value).toHaveProperty("foo");
> ```
> 
> Not only does it bloat the test code unnecessarily, but it also hides the crucial failure information behind an uninformative `false was not true` failure stemming from the `isOk()` check.

I agree that when you expect a Result to equal another Result, it is better to use what you wrote but I don’t see the equivalence for the case where you want to check for a partial match (a property for example).

**Comment by bluenote10** [comment]
That's where you can use `_unsafeUnwrap`, i.e. just:

```ts
expect(result._unsafeUnwrap()).toHaveProperty("foo");
```

If the `result` wasn't okay, the `_unsafeUnwrap` would fail and give a good test failure message.

**Comment by paduc** [comment]
Ok thanks @bluenote10 I got it ! 👍

I’ve got 200 tests to refactor now 😅

**Comment by supermacro** [comment]
In tests, it's fine to use the `_unsafe` api. Consider the `_unsafe` apis as utility methods specifically for testing.

FWIW, at my company, we've turned off `eslint-plugin-neverthrow` in test files.
