### ISSUE TITLE
Guarantees on promise rejection

### ISSUE THREAD

**Issue by davazp** [supermacro/neverthrow#257]
Hi, the README.md carefully advises against having exceptions/rejections when working with the library.

In particular, the `fromSafePromise` function mentions:

> Ensure you know what you're doing, otherwise a thrown exception within this promise will break any guarantees that neverthrow provides.

Now, I would like to encode expected/regular errors in the Result type, but allow unexpected/rare/fatal errors to reject my promises.

Looking at the code, this library seems to allow that, but the documentation kind of suggests that that is not okay and the compatibility could break later on after some changes.

What is the position on that?  I can always not use `ResultAsync` and encode my functions as `Promise<Result<T,E>>` manually, but it is kind of a pity, because `ResultAsync` methods are pretty useful.

**Comment by supermacro** [comment]
Hey @davazp, 

Great question, and something I should probably bring up more explicitly in the docs.

I think there isn't a clear-cut answer and it's about a team's / individual's preference on how they want to deal with / think about "irrecoverable errors". 

I would say that most people in the functional programming community (and Rust?) would agree with me when I say that you should encode recoverable errors into your type system (i.e. in your `Result` types), and have a separate process / system in place for irrecoverable errors. 

For servers, that means - shut down your server because something horribly wrong has just occurred and your server is now in a non-sensical state. An example of this would be if you're missing critical environment variables. In some of my applications, I `throw` and have a `process.on('UnhandledException', () => {})` handler that terminates the server safely.

The rust community has done a great job of documenting this distinction between recoverable vs irrecoverable errors:

https://doc.rust-lang.org/stable/book/ch09-00-error-handling.html

**Comment by davazp** [comment]
I think that is fair. But I do take it further  and would like to give the user the ability to decide how granularly they want to handle errors.

In my opinion, is not so just about crashing the server, but if the way you handle the error being straightforward, and you don't think is worth making the types more complex for it.

For example, in many apps, if my DB is down and I can't connect to the database,  I don't want to make all the code more complex for such an edge case.   And the handling of such an error is simple,  just set a 5xx.

If, on the other hand, I want to have a retry policy or serve some alternative content or short-circuit to another storage, I would want to encode it in the return type, so I benefit from the types.

Other's opinions can be different, but it is how I like to do it.  _Take benefit of the type system for the cases that do matter_.

So, with that in mind, the question is:

**Should this library explicitly support this, by stating the behavior if a promise is rejected inside a ResultAsync**?  

For example, if you do `resultAsync.andThen(()=> ..somethign that throws )`,   then the returning resultAsync will _reject_.

Again, I think this is how it behaves now.  But the documentation about `fromSafePromise` says those things can break all guarantees.

**Comment by supermacro** [comment]
I totally agree with you. 

There is no implicit or explicit mechanism in place right now to "swallow" thrown exceptions inside of a `Result` / `ResultAsync`. 

When I wrote commentary about "breaking guarantees" it was more about the fact that something that may be pure by the looks of it, may not actually be pure because something inside the "result stack" is throwing exceptions - thus defeating the purpose of having a complex "result stack" (because you still need a `catch` somewhere high on the stack).

So, my point is, I personally support this convention. But it's something where you need to know what you're doing / needs to be done with intention.

I guess the "fix" to this GitHub issue is simply to update the README or add an entry into the wiki? I would gladly accept a contribution on this - especially a wiki article.

**Comment by davazp** [comment]
> I guess the "fix" to this GitHub issue is simply to update the README or add an entry into the wiki? I would gladly accept a contribution on this - especially a wiki article.

I think so!  I'll try to sketch something next week.  Thanks!

**Comment by supermacro** [comment]
Closing because docs have been updated as of #269
