### ISSUE TITLE
Simplify / organize docs

### ISSUE THREAD

**Issue by supermacro** [supermacro/neverthrow#38]
I am seeking suggestions on how to make the documentation easier to discover and learn.

I am considering using gitbook.com ... Any other suggestions?

**Comment by paduc** [comment]
Gitbook is great. I'll be happy to lend a hand.

I think one improvement would be to start right away a real use-case example, to show the pain-point and the solution `neverthrow` offers.

Also, now that the api is pretty long, I would add a simple list of all methods signatures and a link to their specific paragraph. I think by looking at the signatures, you gets a sense of which method you're going to need.

**Comment by supermacro** [comment]
> I think one improvement would be to start right away a real use-case example, to show the pain-point and the solution neverthrow offers.

I think that linking to my blog post is the right thing to do for those that aren't familiar with the purpose of this library. I wouldn't want to add a whole section explaining "why" within the README.

> Also, now that the api is pretty long, I would add a simple list of all methods signatures and a link to their specific paragraph. I think by looking at the signatures, you gets a sense of which method you're going to need.

Yeah that's a great idea. 

Something like this maybe?

----

### API Overview

- `Result` (Synchronous API [#](#link-to-syncronous-api))
  - `ok` 
  - `err`
  - `.map`
  - `.mapErr`
  - ...
  - ...
- `ResultAsync` (Asynchronous API [#](#link-to-asyncronous-api))
  - `.fromPromise` (static)
  - `okAsync`
  - `errAsync`
  - `.map`
  - ...
  - ...


### `Result` - Synchronous API

blah blah blah 

....


### `AsyncResult` - Asynchronous API

blah blah blah 

...

**Comment by paduc** [comment]
Yes, exactly, a sort of "Table of contents". 
I would add two things:
- A pseudo type signature (not necessarily typescript but enough to get "Oh map transforms the value type" really fast)
- A link for each method

Like this maybe:

## API Overview

 * `Result` (Synchronous API [#](#link-to-syncronous-api))
   
   * [`ok(T) => Ok<T,?>`](#link-to-specific-api)
   * [`err(E) => Err<?,E>`](#link-to-specific-api)
   * [`.map(T => U) => Result<U,E>`](#link-to-specific-api)
   * [`.mapErr(E1 => E2) => Result<T,E2>`](#link-to-specific-api)
   * ...
   * ...
 * `ResultAsync` (Asynchronous API [#](#link-to-asyncronous-api))
   
   * [`.fromPromise(Promise<T>, ? => E) => ResultAsync<T,E>`](#link-to-specific-api)
   * [`okAsync(T) => ResultAsync<T,?>`](#link-to-specific-api)
   * [`errAsync(E) => ResultAsync<?, E>`](#link-to-specific-api)
   * [`.map(T => U) => ResultAsync<U, E>`](#link-to-specific-api)
   * [`.mapErr(E1 => E2) => ResultAsync<T, E2>`](#link-to-specific-api)
   * [`.andThen(T => Result<U> | ResultAsync<U>) => ResultAsync<U, E>`](#link-to-specific-api)
   * ...
   * ...

**Comment by TheFalseFriend** [comment]
@supermacro I'd also suggest adding a section that discusses how to handle side-effects; what is the best practice in the context of ```neverthrow```? Why?

Specifically, I'm referring to cases in which we've got an operation that runs and invokes some side effect, or otherwise fails (and where we might not really care what the result of the side effect was - we just care it happened without error).

I guess ideally, if I'm trying to keep things functional, I'd avoid side effects in the first place. Instead I'd ensure called code always returns an ```ok(stuff)``` or an ```err(stuff)```.  However there are conceivable situations in which the 'contents' of a 'success' are not of concern (but where the 'contents' of an 'error' remain a concern). 

For instance, say we have a function that sends an email when called. Actually sending the message is handled by a library (abstracting an HTTP mail API). This library might throw (e.g perhaps if the underlying REST service was unavailable). This might be implemented as follows:

```
function sendEmail(recipient: string, body: string) {
    mailLib.send({
        recipient,
        body,
        ... other options / implementation details we abstract from callers ...
    })
}
``` 
Assume everything is synchronous for the sake of simplicity. The intention would be that callers can just invoke this function and proceed. They only care to stop if an error surfaces.

I think documentation discussing how you would use ```neverthrow``` in this sort of situation would be useful, especially for new users.

We could, in theory, wrap whatever ```mailLib#send``` returns after a successful run in a Result<>, this being the return type of _our_ function ```sendEmail``` (with our error type). However, this isn't ideal since:
-  this might be a complex type
- we'd want to avoid exposing the types of the underlying library to the caller (the whole point of our function ```sendEmail``` is to insulate implementation details)
- the underlying library might not return anything of note anyway (e.g. ```void```)

Alternatively, we could just define an empty, general, 'SideEffectSuccess' type. Again this is not ideal since:
- IIRC the TypeScript folk specifically say to avoid defining empty interfaces
- even if this type was nonempty, it seems like bloat when all we wanted to do was denote a side effect

This is an example from a real project I'm working on, that uses the ```sendgrid``` Node lib.  

The more I write here, the more I think this might be a discussion for another Issue! Perhaps a request for an argumentless ```ok```; an ```ok()``` I can return for a function typed ```Result<void, SomeErrorType>``` - or something (```err``` would be unchanged).

Keen to get your thoughts on the above.

Thanks in advance

**Comment by paduc** [comment]
@TheFalseFriend Thanks for those remarks. I was also wondering if `neverthrow` should provide guidance on patterns or stick to the basics. 

Regarding side-effects, by definition your application cannot control them. You definitely can handle the error-case from a `sendMail` service though and it would be appropriate to return a `Result<void, Error>`. There is no argumentless `ok()` but you can return `ok(null)` when the return type is `void`. It's more typing but it makes things more explicit.

In PR #44 another user ended up adding methods that, in my opinion, enabled a bad practice. I believe the proper patterns for using `neverthrow` efficiently are not obvious. 

One such pattern I use all the time is to try to avoid the actual unwrapping of a `Result` for as long as possible. If all your internal methods return a `Result` or `ResultAsync`, it's possible (and I believe preferable) to chain them to produce another `Result` / `ResultAsync`. 

For instance, in the case of an http request that is handled by an application, the handler calls inner methods (to query a database, perform validation, send an email) that all return `Result`s and chains them (using `andThen` for instance), produceing a single top-level `Result`.

At the very end, the handler unwraps that top-level `Result` (using `match` for instance) to either send an error or success payload back to the user.
That way, there is only one single `isErr`/ `isOk` / `match` call per user request.

You may not wish to let the top-level handler sort through every single error that may come up in the belly of the beast. In fact, it's best practice that each domain level handle it's own errors. To do that without calling `isErr` at the intermediate level, you can use `mapErr` and transform domain-specific error types (ex: `DatabaseConnectionLost`) into higher-level error types (ex: `ServiceUnavailable`). 
The top-level handler should only receive User-level error types which can be safely returned to the user.

I'm thinking maybe these sort of patterns could be mentioned in the docs, not as "The Proper Way" but as a suggestion.

**Comment by n8han** [comment]
One thing that would help new users exploring the library is typedocs in the source, so that they'll show up in IDEs. Just the blubs that are already in the readme would be a good start, e.g. for `unwrapOr` "Unwrap the `Ok` value, or return the default if there is an `Err`"

**Comment by supermacro** [comment]
Docs have been cleaned up :) 

Also new version has been published.

https://github.com/supermacro/neverthrow/releases/tag/v3.0.0
