### ISSUE TITLE
[Question] : Performance of combine. 

### ISSUE THREAD

**Issue by LeakStephane** [supermacro/neverthrow#534]
Hey, first let me thank your library which is overall wonderful. 

## Issue :

I run into trouble regarding the `Result.combine` method. 
I'm basically trying to combine a relatively "huge" `array` around 300_000 elements of `Result<T, E>`. 
Sadly doing so takes around 1 minutes on my computer.

## Question : 

Is `combine` implementation ready to handle that size of array  ?

P.S : For now i will just not use `neverthrow` on array that are too big.

**Comment by supermacro** [comment]
Oh wow, that's an interesting use case. 

![image](https://github.com/supermacro/neverthrow/assets/10621548/1426ce15-88fc-49b2-b8a2-895f9201910e)

So the implementation of `Result.combine` is relatively straightforward. 

There are two issues I see immediately (with respect to large result lists):

- O(n) runtime due to usage of `resultList.reduce`
  - this is def not the main problem though, as looping 300,000 elements on my machine on a for loop took about 4 seconds
- `appendValueToEndOfList` is creating a new array on each iteration :fearful: 

The latter issue is almost certainly the problem.

That being said, as I've mentioned [here](https://github.com/supermacro/neverthrow/issues/531), I don't have time to contribute to the codebase. 

That being said though I would be happy to accept a fix for this.

**Comment by supermacro** [comment]
Also, `...list` is expanding the previous list (in addition to the problem of creating a brand new array). This is also very likely another cause of the performance slowdown.

**Comment by supermacro** [comment]
On another note; given such a large list, would you not want some sort of function that partitions your results into `Ok` values and `Err` values?

e.g.

```typescript
const [okList, errList] = Result.partition(veryLargeList)

```

**Comment by LeakStephane** [comment]
Hey, thank for you detailed answer ! 

--------------

> That being said, as I've mentioned https://github.com/supermacro/neverthrow/issues/531, I don't have time to contribute to the codebase.

Yeah, i saw the message. I'm glad that your are transparent on the time you can dedicate to `neverthrow`. 👍 

Also good luck in your new startup adventure, i know from experience that it's time consuming 😉 

--------------

> That being said though I would be happy to accept a fix for this - and I'll devote time to reviewing the PR.

I will definitively have a look, but `no promises`  😃

-------------

> On another note; given such a large list, would you not want some sort of function that partitions your results into Ok values and Err values?

Yeah, could be nice, should be useful in my case. 

(**_This is a personal opinion_**) 

That being said, in general i'm not in favor of expanding the interface of make it more confusing and hard to learn other time. 

I need to check but it might be doable to do some kind of `partition` without relaying on a method implemented by `neverthrow`. 

-----------------

Overall nice pinpointing of the issue 👍

**Comment by flowreaction** [comment]
Another issue with the current implementation, that isn't directly connected to this issue though, is that even when isErr() returns true, the reduce will keep iterating over the entire input list. So not really short circuiting but only returning err(result.error) n times before it finally finishes all elements.

I played around with the implementation and this here is magnitudes faster on my machine.

this implementation doesn't create new arrays in every iteration but mutates one array a bunch of times.
I am not too familiar with this package yet which is why i resorted to the unsafeUnwrap, which is probably not a good idea right?

```ts
export const combineResultListFast = <T, E>(
  resultList: readonly Result<T, E>[],
): Result<readonly T[], E> => {
  let acc = ok([]) as Result<T[], E>

  for (const result of resultList) {
    if (result.isErr()) {
      acc = err(result.error)
      break
    } else {
      acc.isOk() && acc._unsafeUnwrap().push(result.value)
    }
  }
  return acc
}
```

i benchmarked it with a couple of different input sizes and this is the result of the microbenchmark on my machine:
```┌─────────┬─────────────┬─────────────────────┬──────────────────────┬────────────────┬────────────────────┐
│ (index) │ numElements │ timeOld             │ timeNew              │ areResultsSame │ improvement        │
├─────────┼─────────────┼─────────────────────┼──────────────────────┼────────────────┼────────────────────┤
│ 0       │ 100         │ 0.07845900000000938 │ 0.032834000000008245 │ true           │ 2.3895656940972674 │
│ 1       │ 1000        │ 1.1687090000000069  │ 0.10370899999999494  │ true           │ 11.269118398596687 │
│ 2       │ 10000       │ 36.65729200000001   │ 0.5931250000000148   │ true           │ 61.80365353003009  │
│ 3       │ 100000      │ 8476.178375000001   │ 0.8193340000016178   │ true           │ 10345.205221537572 │
└─────────┴─────────────┴─────────────────────┴──────────────────────┴────────────────┴────────────────────┘
```

**Comment by flowreaction** [comment]
Addionally, it might also make sense to refactor the `combineResultListWithAllErrors()` function to not use reduce + spread as reduce and spread in combination is always slow for large data sets in comparison with regular loops and array mutation. See this jsperf benchmark: https://jsperf.app/noyulo

```ts
export const combineResultListWithAllErrors = <T, E>(
  resultList: readonly Result<T, E>[],
): Result<readonly T[], E[]> => {
  let acc = ok([]) as Result<T[], E[]>

  for (const result of resultList) {
    if (result.isErr() && acc.isErr()) {
      acc.error.push(result.error)
    } else if (result.isErr() && acc.isOk()) {
      acc = err([result.error])
    } else if (result.isOk() && acc.isErr()) {
      // do nothing
    } else if (result.isOk() && acc.isOk()) {
      acc.value.push(result.value)
    }
  }
  return acc
}
```
